import ClientStack from 'core/stack';
/**
 * Executes a query plan against the in-memory database.
 * This function orchestrates fetching data, joining, filtering, aggregating,
 * projecting, sorting, and limiting the results.
 * @param {object} stack The ClientStack instance providing data access.
 * @param {object} plan The query plan generated by the planner.
 * @param {Array<any>} params A list of parameters for prepared statements (not used in this version).
 * @param {object | null} outerRow The data row from an outer query for correlated subqueries.
 * @param {object | null} outerAliases The aliases from an outer query.
 * @returns {Promise<Array<object>>} A promise that resolves to the final query results.
 * @throws {Error} If a table specified in the query is not found.
 */
export declare function executePlan(stack: ClientStack, plan: any, params: any, outerRow?: null, outerAliases?: null): Promise<any>;
