/**
 * Creates a logical query plan from a list of Abstract Syntax Trees (ASTs) for a UNION query.
 * @param {Array<object>} astList The list of ASTs generated by the parser.
 * @returns {object} A query plan object for the executor.
 */
export declare function createPlan(astList: any): {
    type: string;
    distinct: any;
    fromTable: any;
    joins: never[];
    filters: {
        left: never[];
        right: {};
        residual: never[];
    };
    projections: any;
    aggregation: null;
    orderBy: any;
    limit: any;
} | {
    type: string;
    selectPlans: never[];
    unionOps: never[];
    orderBy: null;
    limit: null;
} | null;
