#!/usr/bin/env bash
# Regenerates the vendored WASM artifacts from rust/. Requires the Rust
# toolchain with the wasm32-unknown-unknown target and wasm-bindgen-cli
# matching the wasm-bindgen version in Cargo.lock.
set -euo pipefail
cd "$(dirname "$0")/../rust"
cargo build --release --target wasm32-unknown-unknown
wasm-bindgen --target web --out-dir pkg-web target/wasm32-unknown-unknown/release/abe_rabe_wasm.wasm
cp pkg-web/abe_rabe_wasm.js ../src/wasm/glue.js
cp pkg-web/abe_rabe_wasm.d.ts ../src/wasm/glue.d.ts
node -e "
const fs = require('fs');
const b64 = fs.readFileSync('pkg-web/abe_rabe_wasm_bg.wasm').toString('base64');
fs.writeFileSync('../src/wasm/bytes.js',
  '// GENERATED by scripts/build-wasm.sh from rust/ (rabe AC17 CP-ABE, wasm32-unknown-unknown).\n// Do not edit.\nexport const WASM_BASE64 = ' + JSON.stringify(b64) + ';\n');
"
echo "regenerated src/wasm artifacts"
