import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Explicit ids on purpose: a page missing from disk fails the build instead of
// silently dropping out of navigation.
const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Get started',
      collapsed: false,
      items: ['get-started/installation', 'get-started/quickstart', 'get-started/examples'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/model-your-data',
        'guides/triggers',
        'guides/jobs',
        'guides/query-with-sql',
        'guides/encrypt-fields',
        'guides/access-scopes',
        'guides/write-transactions',
        'guides/patches',
        'guides/sync',
        'guides/google-drive',
        'guides/filtering',
        'guides/react',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/core-concepts',
        'concepts/offline-first-and-sync',
        'concepts/schema-engine',
        'concepts/query-engine',
        'concepts/crypto-engine',
        {
          type: 'category',
          label: 'Access control',
          link: { type: 'doc', id: 'concepts/access-control/index' },
          items: [
            'concepts/access-control/policy-model',
            'concepts/access-control/crypto-access',
            'concepts/access-control/architectures',
            'concepts/access-control/threat-model',
            'concepts/access-control/recipes',
          ],
        },
        'concepts/transaction-engine',
        'concepts/patches',
        'concepts/security',
        'concepts/under-the-hood',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/class-and-attribute-options',
        'reference/trigger-and-job-models',
        'reference/scheduler-options',
        'reference/sync-options',
        'reference/patch-format',
        'reference/internal-documents',
        'reference/sql-dialect',
        'reference/server',
        {
          type: 'category',
          label: 'API reference',
          items: [
            { type: 'ref', id: 'api/client/index', label: '@docstack/client' },
            { type: 'ref', id: 'api/react/index', label: '@docstack/react' },
            { type: 'ref', id: 'api/abe/index', label: '@docstack/abe' },
            { type: 'ref', id: 'api/server/index', label: '@docstack/server (preview)' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/monorepo-and-builds',
        'contributing/schema-propagation-internals',
        'contributing/decision-records',
        'contributing/roadmap',
      ],
    },
  ],
  apiClient: [{ type: 'autogenerated', dirName: 'api/client' }],
  apiReact: [{ type: 'autogenerated', dirName: 'api/react' }],
  apiAbe: [{ type: 'autogenerated', dirName: 'api/abe' }],
  apiServer: [{ type: 'autogenerated', dirName: 'api/server' }],
};

export default sidebars;
