import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {
      type: 'category',
      label: 'Get started',
      collapsible: true,
      collapsed: false,
      items: [
        'get-started/intro',
        'get-started/installation',
        'get-started/goals',
        'get-started/applications',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsible: true,
      collapsed: false,
      items: [
        'architecture/core-concepts',
        'architecture/under-the-hood',
        'architecture/data-models',
        'architecture/infrastructure',
        'architecture/communication',
        'architecture/security',
      ],
    },
    {
      type: 'category',
      label: 'Library',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Client',
          collapsible: true,
          collapsed: false,
          items: [
            'get-started/intro',
            'get-started/installation',
            'get-started/goals',
            'get-started/applications',
          ],
        },
        {
          type: 'category',
          label: 'Server',
          collapsible: true,
          collapsed: false,
          items: [
            'get-started/intro',
            'get-started/installation',
            'get-started/goals',
            'get-started/applications',
          ],
        },
        {
          type: 'category',
          label: 'React',
          collapsible: true,
          collapsed: false,
          items: [
            'get-started/intro',
            'get-started/installation',
            'get-started/goals',
            'get-started/applications',
          ],
        },
      ],
    },
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api', // This should match the 'out' directory from your plugin config
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
